version: '3.8'

services:

  mysql:
    image: mysql:8.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: snippetbox
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./docker/mysql:/var/lib/mysql
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080